"""
An simple file getter entry for chainer model.

@author: FATESAIKOU
@date  : 16/11/2018
"""

from .Interfaces.Ethernet import Scp, Ftp
from .Interfaces.Bluetooth import Obexftp

from .Policies.EzPolicy import DummyPolicy

interface_selector = { "Scp": Scp, "Ftp": Ftp, "Bluetooth": Obexftp }
policy_selector = {"Dummy": DummyPolicy}

class ModelGetter:
    def __init__( self, interface_descriptors, policy_descriptor ):
        # init interfaces
        self.__communicators__ = []
        for if_desc in interface_descriptors:
            if_info = if_desc.split(',')
            if_comm = interface_selector[ if_info[0] ]( *if_info[1:] )

            self.__communicators__.append(if_comm)

        # init policy with profiles generated by communicators
        self.__policy_agent__ = policy_selector[ policy_descriptor ](self.__communicators__)

    def GetModel( self, model_name ):
        # do has files
        ava_comms = [ comm for comm in self.__communicators__
                if comm.HasFile(model_name) ]

        # policy select communicator
        target_comm = self.__policy_agent__.Select(ava_comms)

        # do get file
        report = target_comm.GetFile(model_name)

        # update policy
        self.__policy_agent__.Update(report)
